// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvpR3ZEa6LzGVQFMS5pnfRfmkvj9DIasc',
    appId: '1:655735616729:web:9fd3b4ed99b7cc6d563ac8',
    messagingSenderId: '655735616729',
    projectId: 'ayo-laundry-app',
    authDomain: 'ayo-laundry-app.firebaseapp.com',
    storageBucket: 'ayo-laundry-app.firebasestorage.app',
    measurementId: 'G-KQ1PR3N6HT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFPfMH5Dt15yOwNyVyj3-3pezdZV2usXU',
    appId: '1:655735616729:android:2355804948163a4e563ac8',
    messagingSenderId: '655735616729',
    projectId: 'ayo-laundry-app',
    storageBucket: 'ayo-laundry-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGhDF-c5GIBuUvFO2fuvhGLgpPPnRS-8E',
    appId: '1:655735616729:ios:5565a0d300c6bac2563ac8',
    messagingSenderId: '655735616729',
    projectId: 'ayo-laundry-app',
    storageBucket: 'ayo-laundry-app.firebasestorage.app',
    iosBundleId: 'com.example.ayoLaundryApp',
  );
}
